# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [2]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
np.version.version

'1.20.3'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [4]:
# Method 1
a = np.random.rand(2,3,5)
a

array([[[0.1982332 , 0.36273977, 0.72921533, 0.08275464, 0.05778119],
        [0.10058995, 0.25493287, 0.55837006, 0.94635648, 0.63704384],
        [0.40061635, 0.72384071, 0.02314334, 0.0556303 , 0.2834434 ]],

       [[0.89172931, 0.93715215, 0.52966414, 0.85980306, 0.28936244],
        [0.38355852, 0.13741304, 0.31349861, 0.26691449, 0.19218394],
        [0.25620858, 0.01456982, 0.92722377, 0.99969719, 0.61674715]]])

In [8]:
# Method 2
a = np.random.randint(1,100,(2,3,5))
a

array([[[92, 87, 21, 89, 82],
        [21, 47, 86, 90, 64],
        [84, 84,  4, 31, 54]],

       [[69, 60, 86, 68, 41],
        [43, 17, 74, 98, 76],
        [48, 54, 39, 77, 63]]])

In [10]:
# Method 3
a = np.random.random((2,3,5))
a

array([[[0.15690396, 0.51480705, 0.8497923 , 0.76437967, 0.82955467],
        [0.79928457, 0.75860636, 0.33869879, 0.87605849, 0.90440185],
        [0.13186611, 0.71810642, 0.33740362, 0.84115849, 0.07550893]],

       [[0.39261321, 0.89479247, 0.4432596 , 0.51632681, 0.50514973],
        [0.20223333, 0.56227888, 0.32754833, 0.17094908, 0.27779657],
        [0.41513367, 0.24639149, 0.49350582, 0.29286643, 0.21770437]]])

#### 4. Print *a*.


In [11]:
# your code here
print(a)

[[[0.15690396 0.51480705 0.8497923  0.76437967 0.82955467]
  [0.79928457 0.75860636 0.33869879 0.87605849 0.90440185]
  [0.13186611 0.71810642 0.33740362 0.84115849 0.07550893]]

 [[0.39261321 0.89479247 0.4432596  0.51632681 0.50514973]
  [0.20223333 0.56227888 0.32754833 0.17094908 0.27779657]
  [0.41513367 0.24639149 0.49350582 0.29286643 0.21770437]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [12]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [13]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [15]:
# your code here
print(a.size)
print(b.size)
a.size == b.size

30
30


True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [16]:
# your answer here
a + b

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

I cannot add them because they don't have the same shape

In [18]:
print(a.shape)
print(b.shape)

a.shape == b.shape

(2, 3, 5)
(5, 2, 3)


False

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [30]:
# your code here
c = b.reshape((2,3,5))
print(c.shape)
print(c.shape == a.shape)


(2, 3, 5)
True


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [31]:
# your code/answer here
d = a + c
d

array([[[1.15690396, 1.51480705, 1.8497923 , 1.76437967, 1.82955467],
        [1.79928457, 1.75860636, 1.33869879, 1.87605849, 1.90440185],
        [1.13186611, 1.71810642, 1.33740362, 1.84115849, 1.07550893]],

       [[1.39261321, 1.89479247, 1.4432596 , 1.51632681, 1.50514973],
        [1.20223333, 1.56227888, 1.32754833, 1.17094908, 1.27779657],
        [1.41513367, 1.24639149, 1.49350582, 1.29286643, 1.21770437]]])

It worked this time, because a and c have the same shape now

In [32]:
print(c.shape == a.shape)

True


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [33]:
# your code/answer here
print(a)
print(d)

[[[0.15690396 0.51480705 0.8497923  0.76437967 0.82955467]
  [0.79928457 0.75860636 0.33869879 0.87605849 0.90440185]
  [0.13186611 0.71810642 0.33740362 0.84115849 0.07550893]]

 [[0.39261321 0.89479247 0.4432596  0.51632681 0.50514973]
  [0.20223333 0.56227888 0.32754833 0.17094908 0.27779657]
  [0.41513367 0.24639149 0.49350582 0.29286643 0.21770437]]]
[[[1.15690396 1.51480705 1.8497923  1.76437967 1.82955467]
  [1.79928457 1.75860636 1.33869879 1.87605849 1.90440185]
  [1.13186611 1.71810642 1.33740362 1.84115849 1.07550893]]

 [[1.39261321 1.89479247 1.4432596  1.51632681 1.50514973]
  [1.20223333 1.56227888 1.32754833 1.17094908 1.27779657]
  [1.41513367 1.24639149 1.49350582 1.29286643 1.21770437]]]


The array c was the array of values of 1. Array d came from addition of a to c. Thus every element of array c is greater by 1 from every element of array a.

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [35]:
# your code here
e = a*c
e

array([[[0.15690396, 0.51480705, 0.8497923 , 0.76437967, 0.82955467],
        [0.79928457, 0.75860636, 0.33869879, 0.87605849, 0.90440185],
        [0.13186611, 0.71810642, 0.33740362, 0.84115849, 0.07550893]],

       [[0.39261321, 0.89479247, 0.4432596 , 0.51632681, 0.50514973],
        [0.20223333, 0.56227888, 0.32754833, 0.17094908, 0.27779657],
        [0.41513367, 0.24639149, 0.49350582, 0.29286643, 0.21770437]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [40]:
# your code/answer here

a == e

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

'e' is equal to 'a'. as c was a matrix of values 1, then the multiplication of the matrix a by matrix c didn't change its values. 

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [42]:
# your code here
d_max = np.max(d)
d_max

1.9044018512187542

In [43]:
d_min = np.min(d)
d_min

1.0755089345426487

In [44]:
d_mean = np.mean(d)
d_mean

1.4951693695015187

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [51]:
f = np.empty((2,3,5))
f

array([[[0.15690396, 0.51480705, 0.8497923 , 0.76437967, 0.82955467],
        [0.79928457, 0.75860636, 0.33869879, 0.87605849, 0.90440185],
        [0.13186611, 0.71810642, 0.33740362, 0.84115849, 0.07550893]],

       [[0.39261321, 0.89479247, 0.4432596 , 0.51632681, 0.50514973],
        [0.20223333, 0.56227888, 0.32754833, 0.17094908, 0.27779657],
        [0.41513367, 0.24639149, 0.49350582, 0.29286643, 0.21770437]]])

In [47]:
# your code here
f = np.empty_like(d)
f == a

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [64]:
# your code here
for x in range(2):
	for y in range(3):
		for z in range(5):
			if  d_mean > d[x][y][z] > d_min:
				f[x][y][z] = 25
			elif d_mean < d[x][y][z] < d_max:
				f[x][y][z] = 75
			elif d[x][y][z] == d_mean:
				f[x][y][z] = 50
			elif d[x][y][z] == d_min:
				f[x][y][z] = 0
			elif d[x][y][z] == d_max:
				f[x][y][z] = 100

In [60]:
# your code here
#for ind in range(d.size): 
	#print(d[ind])
#for x in d:
	#for y in x:
		#for z in y:
			#print(z)
print(d[0][0][0])

1.156903962398805


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [65]:
# your code here
print(d)
print(f)

[[[1.15690396 1.51480705 1.8497923  1.76437967 1.82955467]
  [1.79928457 1.75860636 1.33869879 1.87605849 1.90440185]
  [1.13186611 1.71810642 1.33740362 1.84115849 1.07550893]]

 [[1.39261321 1.89479247 1.4432596  1.51632681 1.50514973]
  [1.20223333 1.56227888 1.32754833 1.17094908 1.27779657]
  [1.41513367 1.24639149 1.49350582 1.29286643 1.21770437]]]
[[[ 25.  75.  75.  75.  75.]
  [ 75.  75.  25.  75. 100.]
  [ 25.  75.  25.  75.   0.]]

 [[ 25.  75.  25.  75.  75.]
  [ 25.  75.  25.  25.  25.]
  [ 25.  25.  25.  25.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [75]:
g = []

for elem in np.nditer(d):
	if d_mean > elem > d_min:
		g += 'B'
	elif d_mean < elem < d_max:
		g += 'D'
	elif elem == d_mean:
		g += 'C'
	elif elem == d_min:
		g += 'A'
	else:
		g += 'E'

g = np.reshape(g,(2,3,5))
print(g)
print(d)

[[['B' 'D' 'D' 'D' 'D']
  ['D' 'D' 'B' 'D' 'E']
  ['B' 'D' 'B' 'D' 'A']]

 [['B' 'D' 'B' 'D' 'D']
  ['B' 'D' 'B' 'B' 'B']
  ['B' 'B' 'B' 'B' 'B']]]
[[[1.15690396 1.51480705 1.8497923  1.76437967 1.82955467]
  [1.79928457 1.75860636 1.33869879 1.87605849 1.90440185]
  [1.13186611 1.71810642 1.33740362 1.84115849 1.07550893]]

 [[1.39261321 1.89479247 1.4432596  1.51632681 1.50514973]
  [1.20223333 1.56227888 1.32754833 1.17094908 1.27779657]
  [1.41513367 1.24639149 1.49350582 1.29286643 1.21770437]]]


### Insert dashes


In [17]:
def insert_dash(num):
    '''This function will insert dash into the number between every two odd numbers which are close to each other
	input = number
	output = string with dashes between to consequent odd digits '''
    st_num = str(num)
    output = ''
    for ind in range(len(st_num)-1):
        if int(st_num[ind])%2 !=0 and int(st_num[ind+1])%2 !=0:
            output += st_num[ind] + '-'
        else: 
            output = output + st_num[ind]
    return output + st_num[-1]

In [18]:
insert_dash(123567)

'123-567'

### Thinkful - Logic Drills: Red and bumpy

You're playing a game with a friend involving a bag of marbles. In the bag are ten marbles:

- 1 smooth red marble
- 4 bumpy red marbles
- 2 bumpy yellow marbles
- 1 smooth yellow marble
- 1 bumpy green marble
- 1 smooth green marble
 
You can see that the probability of picking a smooth red marble from the bag is 1 / 10 or 0.10 and the probability of picking a bumpy yellow marble is 2 / 10 or 0.20.

The game works like this: your friend puts her hand in the bag, chooses a marble (without looking at it) and tells you whether it's bumpy or smooth. Then you have to guess which color it is before she pulls it out and reveals whether you're correct or not.

You know that the information about whether the marble is bumpy or smooth changes the probability of what color it is, and you want some help with your guesses.

Write a function color_probability() that takes two arguments: a color ('red', 'yellow', or 'green') and a texture ('bumpy' or 'smooth') and returns the probability as a decimal fraction accurate to two places.

The probability should be a string and should discard any digits after the 100ths place. For example, 2 / 3 or 0.6666666666666666 would become the string '0.66'. Note this is different from rounding.

As a complete example, color_probability('red', 'bumpy') should return the string '0.57'.

In [17]:
def color_probablity(color,texture):
	'''input: color, texture
	output: probabolity of selecting a marbel with that color and texture '''
	#I create 2 dimensional array in which first row is smooth texture, second row is bumpy texture, first column is color red, second column is color yellow and third column is color green
	marbles = np.array([[1,1,1],[4,2,1]])
	if texture == 'bumpy' and color == 'red':
		prob_rb = marbles[1][0]/np.sum(marbles[1])
		return '{0:.2g}'.format(prob_rb)
	elif texture == 'bumpy' and color == 'yellow':
		prob_yb = marbles[1][1]/np.sum(marbles[1])
		return '{0:.2g}'.format(prob_yb)
	elif texture == 'bumpy' and color == 'green':
		prob_gb = marbles[1][2]/np.sum(marbles[1])
		return '{0:.2g}'.format(prob_gb)
	elif texture == 'smooth' and color == 'red':
		prob_rs = marbles[0][0]/np.sum(marbles[0])
		return '{0:.2g}'.format(prob_rs)
	elif texture == 'smooth' and color == 'yellow':
		prob_ys = marbles[0][1]/np.sum(marbles[0])
		return '{0:.2g}'.format(prob_ys)
	else:
		prob_gs = marbles[0][2]/np.sum(marbles[0])
		return '{0:.2g}'.format(prob_gs)


In [4]:
marbles = np.array([[1,1,1],[4,2,1]])
marbles

array([[1, 1, 1],
       [4, 2, 1]])

In [14]:
marbles[1][2]

1

In [12]:
np.sum(marbles[1])

7

In [18]:
color_probablity('red','bumpy')

'0.57'